{
  "AT": "Austria",
  "BE": "Belgium",
  "BG": "Bulgaria",
  "CZ": "Czechia",
  "DE_LU": "Germany–Luxembourg",
  "DK_1": "Denmark West",
  "DK_2": "Denmark East",
  "EE": "Estonia",
  "ES": "Spain",
  "FI": "Finland",
  "FR": "France",
  "GR": "Greece",
  "HR": "Croatia",
  "HU": "Hungary",
  "IT_CALA": "Italy Calabria",
  "IT_CNOR": "Italy Centre North",
  "IT_CSUD": "Italy Centre South",
  "IT_NORD": "Italy North",
  "IT_SARD": "Italy Sardinia",
  "IT_SICI": "Italy Sicily",
  "IT_SUD": "Italy South",
  "LT": "Lithuania",
  "LV": "Latvia",
  "NL": "Netherlands",
  "NO_1": "Norway zone 1",
  "NO_2": "Norway zone 2",
  "NO_3": "Norway zone 3",
  "NO_4": "Norway zone 4",
  "NO_5": "Norway zone 5",
  "PL": "Poland",
  "PT": "Portugal",
  "RO": "Romania",
  "SE_1": "Sweden zone 1",
  "SE_2": "Sweden zone 2",
  "SE_3": "Sweden zone 3",
  "SE_4": "Sweden zone 4",
  "SI": "Slovenia",
  "SK": "Slovakia"
}
